using System;
using System.Collections.Generic;

#nullable disable

namespace Tank.PaymentAPI.Models
{
    public partial class SysUsersDetailModel
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string NickName { get; set; }
        public DateTime Date { get; set; }
        public bool IsConsortia { get; set; }
        public int ConsortiaId { get; set; }
        public bool? Sex { get; set; }
        public int Win { get; set; }
        public int Total { get; set; }
        public int Escape { get; set; }
        public int Gp { get; set; }
        public string Honor { get; set; }
        public int Gold { get; set; }
        public int Money { get; set; }
        public int GoXu { get; set; }
        public string Style { get; set; }
        public string Colors { get; set; }
        public int Hide { get; set; }
        public int Grade { get; set; }
        public int State { get; set; }
        public int IsFirst { get; set; }
        public int Repute { get; set; }
        public DateTime? LastDate { get; set; }
        public DateTime? ChargeDate { get; set; }
        public DateTime? ExpendDate { get; set; }
        public string ActiveIp { get; set; }
        public DateTime ForbidDate { get; set; }
        public string Skin { get; set; }
        public int Offer { get; set; }
        public bool? IsExist { get; set; }
        public int ReputeOffer { get; set; }
        public DateTime? LastDateSecond { get; set; }
        public DateTime? LastDateThird { get; set; }
        public int LoginCount { get; set; }
        public int OnlineTime { get; set; }
        public int AntiAddiction { get; set; }
        public DateTime? AntiDate { get; set; }
        public int RichesOffer { get; set; }
        public int RichesRob { get; set; }
        public int LastDayGp { get; set; }
        public int AddDayGp { get; set; }
        public int LastWeekGp { get; set; }
        public int AddWeekGp { get; set; }
        public int LastDayOffer { get; set; }
        public int AddDayOffer { get; set; }
        public int LastWeekOffer { get; set; }
        public int AddWeekOffer { get; set; }
        public int CheckCount { get; set; }
        public string Site { get; set; }
        public bool IsMarried { get; set; }
        public int SpouseId { get; set; }
        public string SpouseName { get; set; }
        public int MarryInfoId { get; set; }
        public int DayLoginCount { get; set; }
        public string ForbidReason { get; set; }
        public bool IsCreatedMarryRoom { get; set; }
        public string PasswordTwo { get; set; }
        public int SelfMarryRoomId { get; set; }
        public bool IsGotRing { get; set; }
        public string ServerName { get; set; }
        public bool Rename { get; set; }
        public int Nimbus { get; set; }
        public DateTime LastAward { get; set; }
        public int GiftToken { get; set; }
        public byte[] QuestSite { get; set; }
        public string PvePermission { get; set; }
        public int FightPower { get; set; }
        public int AnswerSite { get; set; }
        public DateTime LastAuncherAward { get; set; }
        public int Medal { get; set; }
        public int ChatCount { get; set; }
        public int SpaPubGoldRoomLimit { get; set; }
        public DateTime LastSpaDate { get; set; }
        public string FightLabPermission { get; set; }
        public int SpaPubMoneyRoomLimit { get; set; }
        public bool IsInSpaPubGoldToday { get; set; }
        public bool IsInSpaPubMoneyToday { get; set; }
        public int AchievementPoint { get; set; }
        public DateTime LastWeekly { get; set; }
        public int LastWeeklyVersion { get; set; }
        public int GiftGp { get; set; }
        public int GiftLevel { get; set; }
        public bool IsOpenGift { get; set; }
        public string WeaklessGuildProgressStr { get; set; }
        public bool IsOldPlayer { get; set; }
        public int Score { get; set; }
        public int OptionOnOff { get; set; }
        public bool IsOldPlayerHasValidEquitAtLogin { get; set; }
        public int BadLuckNumber { get; set; }
        public int LuckyNum { get; set; }
        public DateTime LastLuckyNumDate { get; set; }
        public int LastLuckNum { get; set; }
        public int CardSoul { get; set; }
        public int UesedFinishTime { get; set; }
        public int TotemId { get; set; }
        public int DamageScores { get; set; }
        public int PetScore { get; set; }
        public bool IsShowConsortia { get; set; }
        public DateTime LastRefreshPet { get; set; }
        public int Receiebox { get; set; }
        public int ReceieGrade { get; set; }
        public int NeedGetBoxTime { get; set; }
        public int MyScore { get; set; }
        public DateTime LastGetEgg { get; set; }
        public DateTime TimeBox { get; set; }
        public bool? IsFistGetPet { get; set; }
        public int MyHonor { get; set; }
        public int HardCurrency { get; set; }
        public int MaxBuyHonor { get; set; }
        public int LeagueMoney { get; set; }
        public int NecklaceExp { get; set; }
        public int NecklaceExpAdd { get; set; }
        public int GetSoulCount { get; set; }
        public int IsFirstDivorce { get; set; }
        public int CurrentDressModel { get; set; }
        public int MagicStonePoint { get; set; }
        public int DdplayPoint { get; set; }
        public bool? ShareFb { get; set; }
        public bool IsUseLauncher { get; set; }
        public string AchievementProcess { get; set; }
        public bool? IsViewer { get; set; }
        public int ApprenticeshipState { get; set; }
        public int MasterId { get; set; }
        public string MasterOrApprentices { get; set; }
        public int GraduatesCount { get; set; }
        public string HonourOfMaster { get; set; }
        public DateTime FreezesDate { get; set; }
    }
}
